### ISSUE TITLE
Take care of Orphans

### ISSUE THREAD

**Issue by diana-fiverr** [fiverr/i18n.js#26]
Eliminate orphan words by replacing last space with an &NBSP;

**Comment by omrilotan** [comment]
@diana-fiverr Please specify use cases and examples for such a feature request

**Comment by michael5r** [comment]
This shouldn't be a part of the i18n library - changing a space to a non-breaking space impacts layout and text flowing; it's not something to be overridden globally.

**Comment by omrilotan** [comment]
I agree with Michael, but have a solution suggestion #27
